### PR TITLE
WIP: Better potential function

### PR DESCRIPTION
**Pull request by ablondin**
Trying to improve the upper bound strategy. Currently not clear if it improves the performance or not. Wait before merging and any comment or suggestion should be done via this PR.

### CODE REVIEW

**Comment by enadeau** [comment]
For the moment I can figure out why but I think there's a bug with non_subtree_vertices_by_distance. If you try the code:
b=GraphBorder(graphs.WheelGraph(11), upper_bound_strategy='dist')
b.add_to_subtree(1)
b.add_to_subtree(2)
b.add_to_subtree(3)
b.non_subtree_vertices_by_distance
You get
[[], [10, 4], [9, 5], [8, 6]]
I thing there's a layer missing with vertex 7

**Comment by enadeau** [comment]
I think the last commit fixes the bug

**Comment by ablondin** [comment]
Hi, Émile!

I think we both fixed the problem independently. Could you please check if the bug is still present when you checkout commit c27d284? If you confirm it's ok, we could work from there since I have also modified many other parts of the code since then.

**Comment by enadeau** [comment]
Sorry, I can figure out where is your commit and how to checkout. But I think a find a bigger problem with the strategy. If you look at the object just above, your procedure will never choose to add children of 2 since they are of degree one but this is obviously the good way to get many leaves without adding to much inner vertices.
erreur

For the moment if you look at the leaf potential with i=8 for the object, you get -5.

I think the solution is to include the leaves in the partition of the vertices by distance and to follow the procedure below (you can find a bit more detail of my suggestions in the paper)
suggestion

I will eventually try to do the modification on my branch better-potential-and-cube

**Comment by enadeau** [comment]
I will close this pull request. Computing for various values of i doesn't seem to be a good idea. However many of the changes you suggest where useful and should be added to the code. They appear in the pull request #2.

**Pull request closed without merging**
